import {
	type RouteConfig,
	index,
	layout,
	route,
} from "@react-router/dev/routes";

export default [
	route("health", "routes/health.ts"),
	route("login", "routes/login.tsx"),
	route("auth/verify", "routes/auth-verify.ts"),
	route("api/scraper/organizations", "routes/api-scraper-organizations.ts"),
	route("api/scraper/events", "routes/api-scraper-events.ts"),
	route("invite/accept", "routes/invite-accept.tsx"),
	route("logout", "routes/logout.ts"),
	route("media/*", "routes/media.ts"),
	layout("routes/dashboard-layout.tsx", [
		index("routes/home.tsx"),
		route("members", "routes/members.tsx"),
		route("members/:memberId", "routes/member-detail.tsx"),
		route("profile", "routes/profile.tsx"),
		route("notifications", "routes/notifications.tsx"),
		route("events/moderation", "routes/event-moderation.tsx"),
		route("posts/new", "routes/post-new.tsx"),
		route("posts/:postId/edit", "routes/post-edit.tsx"),
		route("posts/:postId", "routes/post-detail.tsx"),
		route("organizations", "routes/organizations.tsx"),
		route("organizations/:slug/manage", "routes/organization-manage.tsx"),
		route("organizations/:slug", "routes/organization-detail.tsx"),
		route("admin/affiliations", "routes/admin-affiliations.tsx"),
		route("admin", "routes/admin.tsx"),
		route("admin/audit", "routes/admin-audit.tsx"),
		route("admin/organizations", "routes/admin-organizations.tsx"),
		route("admin/scraper", "routes/admin-scraper.tsx"),
		route("admin/invitations", "routes/admin-invitations.tsx"),
		route("admin/members", "routes/admin-members.tsx"),
		route(":section", "routes/section.tsx"),
	]),
] satisfies RouteConfig;
